In [1]:
import tensorflow as tf
print(tf.__version__)


2.16.1


In [2]:
import sys
print(sys.executable)


C:\Users\sarayu krishna\my_project\venv\Scripts\python.exe


In [3]:
 

# Define two constant tensors
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0, dtype=tf.float32)

# Define an operation
c = tf.add(a, b)

# Run the graph
print("a:", a)
print("b:", b)
print("a + b:", c)


a: tf.Tensor(3.0, shape=(), dtype=float32)
b: tf.Tensor(4.0, shape=(), dtype=float32)
a + b: tf.Tensor(7.0, shape=(), dtype=float32)


In [4]:
 
# creating nodes in computation graph
node1 = tf.constant(3, dtype=tf.int32)
node2 = tf.constant(5, dtype=tf.int32)
node3 = tf.add(node1, node2)

# evaluating node3 and printing the result
print("sum of node1 and node2 is :", node3)
# closing the session
 

sum of node1 and node2 is : tf.Tensor(8, shape=(), dtype=int32)


In [5]:
scalar = 5
print("rank:",tf.rank(scalar).numpy)


rank: <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=0>>


In [6]:
vector=tf.constant([11,1,4])
print("rank",tf.rank(vector).numpy)
print("shape",vector.shape)

rank <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=1>>
shape (3,)


In [7]:
# 3D Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("\n3D Tensor:")
print("Rank:", tf.rank(tensor_3d).numpy())
print("Shape:", tensor_3d.shape)


3D Tensor:
Rank: 3
Shape: (3, 2, 2)


In [8]:
tensor_4d = tf.constant([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("\n4D Tensor:")
print("Rank:", tf.rank(tensor_4d).numpy())
print("Shape:", tensor_4d.shape)


4D Tensor:
Rank: 4
Shape: (2, 2, 2, 2)


In [9]:
 

# Define constants
const_scalar = tf.constant(2)
const_vector = tf.constant([1, 2, 3, 4])
const_matrix = tf.constant([[1, 2], [3, 4]])

# Define variables
var_scalar = tf.Variable(2)
var_vector = tf.Variable([1, 2, 3, 4])
var_matrix = tf.Variable([[1, 2], [3, 4]])

# Operations with constants and variables
add_result = const_scalar + var_scalar
mul_result = const_vector * var_vector

# Print results
print("Addition Result:", add_result.numpy())
print("Multiplication Result:", mul_result.numpy())


Addition Result: 4
Multiplication Result: [ 1  4  9 16]


In [10]:
# Define a constant
const_a = tf.constant(5.0, name="const_a")

# Define a variable
var_b = tf.Variable(3.0, name="var_b")


In [11]:
# Trying to modify the constant value will raise an error
try:
    const_a.assign(10.0)  # This will raise an error
except AttributeError as e:
    print(f"Error when trying to modify a constant: {e}")

# Modify the variable value
var_b.assign(10.0)
print("Modified variable var_b:", var_b.numpy())


Error when trying to modify a constant: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'
Modified variable var_b: 10.0


In [12]:
# Define another constant and variable
const_c = tf.constant(2.0, name="const_c")
var_d = tf.Variable(4.0, name="var_d")

# Perform operations
result_const = const_a * const_c  # Constant * Constant
result_var = var_b * var_d        # Variable * Variable

print("Result of constant operation (const_a * const_c):", result_const.numpy())
print("Result of variable operation (var_b * var_d):", result_var.numpy())


Result of constant operation (const_a * const_c): 10.0
Result of variable operation (var_b * var_d): 40.0


In [13]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Print the original shape
print("Original Shape:", tensor.shape)

# Reshape the tensor to a different shape
reshaped_tensor = tf.reshape(tensor, [3, 2])

# Print the reshaped tensor and its shape
print("Reshaped Tensor:", reshaped_tensor)
print("Reshaped Shape:", reshaped_tensor.shape)


Original Shape: (2, 3)
Reshaped Tensor: tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Reshaped Shape: (3, 2)


In [14]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,3]

In [15]:
print(tensor1)
print(tensor2)
print(tensor3)
# Notice the changes in shape

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


 <br>*


**SLICING**

In [16]:
 

# Create a 3x3 tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original Tensor:")
print(tensor)

# Slice to get the first two rows and all columns
slice1 = tensor[:2, :]
print("\nSlice 1 (first two rows and all columns):")
print(slice1)

# Slice to get the last two columns of the second row
slice2 = tensor[1, 1:]
print("\nSlice 2 (last two columns of the second row):")
print(slice2)

# Slice to get the last row and the first two columns
slice3 = tensor[2, :2]
print("\nSlice 3 (last row and first two columns):")
print(slice3)

# Slice to get a submatrix (e.g., center 2x2 matrix)
slice4 = tensor[1:3, 1:3]
print("\nSlice 4 (center 2x2 matrix):")
print(slice4)


Original Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

Slice 1 (first two rows and all columns):
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Slice 2 (last two columns of the second row):
tf.Tensor([5 6], shape=(2,), dtype=int32)

Slice 3 (last row and first two columns):
tf.Tensor([7 8], shape=(2,), dtype=int32)

Slice 4 (center 2x2 matrix):
tf.Tensor(
[[5 6]
 [8 9]], shape=(2, 2), dtype=int32)
